# Generated by Django 5.1.2 on 2024-12-11 18:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("predictor", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="trainedmodel",
            name="coefficients",
        ),
        migrations.RemoveField(
            model_name="trainedmodel",
            name="intercept",
        ),
        migrations.AddField(
            model_name="trainedmodel",
            name="architecture",
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="trainedmodel",
            name="weights",
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
