# Generated by Django 5.1.2 on 2024-12-03 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("understat", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("team_id", models.IntegerField()),
                ("title", models.CharField(max_length=100)),
                ("short_title", models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name="Match",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("match_id", models.IntegerField()),
                ("is_result", models.BooleanField()),
                ("home_goals", models.IntegerField()),
                ("away_goals", models.IntegerField()),
                ("home_xg", models.FloatField()),
                ("away_xg", models.FloatField()),
                ("datetime", models.DateTimeField()),
                ("forecast_win", models.FloatField()),
                ("forecast_draw", models.FloatField()),
                ("forecast_loss", models.FloatField()),
                (
                    "away_team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="away_matches",
                        to="understat.team",
                    ),
                ),
                (
                    "home_team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="home_matches",
                        to="understat.team",
                    ),
                ),
            ],
        ),
    ]
